version: '3.5'
volumes:
  database-data:
  redis-data:
  influx-data:
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
  browser:
    dns:
      - 94.140.14.15
      - 94.140.15.16
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 16
      NODE_MAX_INSTANCES: 16
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
    links:
      - hub
  postgres:
    image: postgres:10
    ports:
      - 19371:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data
    volumes:
      - database-data:/data
  redis:
    image: redis:4.0.10
    ports:
      - 7779:6379
  influxdb:
    image: influxdb:2.0.7
    network_mode: 'host'
    volumes:
      - influx-data:/var/lib/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_DB=stonks
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - DOCKER_INFLUXDB_INIT_USERNAME=stonks
      - DOCKER_INFLUXDB_INIT_PASSWORD=stonks_pirate
      - DOCKER_INFLUXDB_INIT_ORG=stonks
      - DOCKER_INFLUXDB_INIT_BUCKET=stonks